# for Portainer
services:
  app:
    image: ghcr.io/kacperwyczawski/elektronet:main
    volumes:
      - database:/app/volume
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elektronet.rule=Host(`elektronet.zse.rzeszow.pl`)"
      - "traefik.http.services.elektronet.loadbalancer.server.port=80"
    networks:
        - traefik
      
networks:
  traefik:
    name: traefik_proxy
    external: true

volumes:
  database: